---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: redpencil/virtuoso
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: redpencil/virtuoso
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: redpencil/virtuoso
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: SK1quBqa3EJ1vrWvsI2ISu8bpOYUXGOxy3SqmtTBOfbFL7jv1Hxo
---
kind: secret
name: docker_password
data: WFMLjNKGW2WhJYCSxikdY9vBoCTk/Tfar2JjJscqeQEaQCnBdopidkMTbhVKiTIsrWk0bGdBEMwDkFceP55pHQ==
---
kind: signature
hmac: 683ebb21c6c649dbf2be3e358cf7b582ae150bc5668572c814e03971f1f94611

...
