pipeline:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: redpencil/virtuoso
      dry_run: true
      platforms: linux/amd64,linux/arm64
when:
  event:
    - pull_request
