pipeline:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker_username, docker_password ]
    settings:
      repo: redpencil/virtuoso
      tags: ${CI_COMMIT_SOURCE_BRANCH/\//-}
      platforms: linux/amd64
when:
  event:
    - pull_request
  branch: feature/*
