pipeline:
  build-and-release:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [ docker_username, docker_password ]
    settings:
      repo: redpencil/virtuoso
      platforms: linux/amd64,linux/arm64
      tags: ${CI_COMMIT_TAG##v} # strips v from the tag
when:
  event: tag
  tag: v*
